services:
  - type: web
    name: screenshot-api
    env: python
    buildCommand: pip install -r requirements.txt && pyppeteer-install
    startCommand: gunicorn app:app --timeout 180 --workers 1 --threads 2 --worker-tmp-dir /dev/shm --max-requests 10 --max-requests-jitter 5
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 1
